# Except for the secret key, none of these are actually needed; Rocket has sane
# defaults. We show all of them here explicitly for demonstrative purposes.

[default.limits]
forms = "64 kB"
json = "1 MiB"
msgpack = "2 MiB"
"file/jpg" = "5 MiB"

[default]
key = "a default app-key"
extra = false
ident = "Rocket"
ip_header = "CF-Connecting-IP"

[debug]
address = "127.0.0.1"
port = 8000
workers = 1
keep_alive = 0
log_level = "normal"

[release]
address = "127.0.0.1"
port = 8000
workers = 12
keep_alive = 5
log_level = "critical"
# NOTE: generate key via `head -c64 /dev/urandom | base64`
secret_key = "WvY7u+RB15sMtw6ywwvZZir85glEK3RAWiWo57VFFbxk+ma8YbbUGWePBi7LC9VsC6xtOe8QgFT5DJ9lz4IkzA=="
key = "a release app-key"
extra = false